spring:
  activemq:
    broker-url: tcp://127.0.0.1:61616
    user: admin
    password: admin
    in-memory: true
    close-timeout: 30000
    pool:
      enabled: true
      idle-timeout: 30000
      max-connections: 100
